name: DevTools
main: DevTools\DevTools
version: 2.0-LDX
api: 1.3.1
load: STARTUP
author: The PocketMine Team & LDX
description: "A collection of tools made to help PocketMine-MP plugin developers."
website: "https://github.com/LDX-MCPE/DevTools"
commands:
  makeserver:
    description: "Compiles a copy of PocketMine-MP into a Phar."
    usage: "/makeserver"
    permission: devtools.command.makeserver
  makeplugin:
    description: "Compiles a loaded plugin into a Phar."
    usage: "/makeplugin <plugin>"
    permission: devtools.command.makeplugin
permissions:
  devtools:
    default: false
    description: "Allows access to all DevTools features."
    children:
      devtools.command:
        default: false
        description: "Allows access to all DevTools commands."
        children:
          devtools.command.makeplugin:
            default: op
            description: "Allows access to the makeplugin command."
          devtools.command.extractplugin:
            default: op
            description: "Allows access to the extractplugin command."
          devtools.command.makeserver:
            default: op
            description: "Allows access to the makeserver command."
